name: single

on:
  workflow_dispatch:

jobs:
  build:
    name: Build - ${{ matrix.target.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - arch: "x86_64"
            sdk: "https://downloads.openwrt.org/releases/22.03.5/targets/x86/64/openwrt-sdk-22.03.5-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz"
    steps:
      - uses: actions/checkout@v2
      - name: Install build requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
          gettext git java-propose-classpath libelf-dev libncurses5-dev \
          libncursesw5-dev libssl-dev python3 unzip wget \
          python3-distutils python3-setuptools python3-dev rsync subversion \
          swig time xsltproc zlib1g-dev

      - name: Install OpenWrt SDK
        run: |
          wget -O openwrt-sdk.tar.xz ${{ matrix.target.sdk }}
          xz -q -d openwrt-sdk.tar.xz && tar -xvf openwrt-sdk.tar
          mv -f openwrt-sdk-* openwrt-sdk
      - name: Build Package
        run: |
          echo "src-link netbird $GITHUB_WORKSPACE" > openwrt-sdk/feeds.conf
          echo 'CONFIG_PACKAGE_netbird=y
          ' >> openwrt-sdk/.config
          cd openwrt-sdk

          git clone https://github.com/kuoruan/openwrt-upx.git package/upx
          git -C package/upx checkout 2c2ee0d696ea6084bee893a2861a7ed0729728ed # upx version: v2022-10-20

          #cat feeds.conf.default >> feeds.conf
          echo 'src-git packages https://git.openwrt.org/feed/packages.git;openwrt-23.05' >> feeds.conf # feeds/packages: OpenWrt v23.05.0-latest
          cat feeds.conf

          ./scripts/feeds update -a > /dev/null
          rm -rf ./feeds/packages/net/netbird
          make defconfig

          ./scripts/feeds install -d y -f -a
          make package/netbird/compile V=s CONFIG_NETBIRD_COMPRESS_UPX=y
          tree bin/packages/
      - name: Archive package
        uses: actions/upload-artifact@v2
        with:
          name: netbird-${{ matrix.target.arch }}
          path: openwrt-sdk/bin/packages/*/netbird/netbird*.ipk
          if-no-files-found: error
      - name: Upload package to GitHub Release
        uses: svenstaro/upload-release-action@v2
        if: "startsWith(github.ref, 'refs/tags/')"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          overwrite: true
          file: openwrt-sdk/bin/packages/*/netbird/netbird*.ipk
          tag: ${{ github.ref }}
