name: Update netbird version

on:
  workflow_dispatch:
  schedule:
    # Run every week
    - cron: '0 2 * * *'
jobs:
  update:
    name: Update netbird version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install requirements
      run: pip install requests
    - name: Update
      id: update
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python .github/update.py
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.update.outputs.NETBIRD_VERSION }}
        release_name: v${{ steps.update.outputs.NETBIRD_VERSION }}
        draft: false
        prerelease: false
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        branch: update-netbird-version
        delete-branch: true
        add-paths: |
          netbird/Makefile
        title: 'Update netbird to v${{ steps.update.outputs.NETBIRD_VERSION }}'
        commit-message: 'Update netbird to v${{ steps.update.outputs.NETBIRD_VERSION }}'
